version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Paris"
    assignees:
      - "antoinezanardi"
    reviewers:
      - "antoinezanardi"
    commit-message:
      prefix: "chore(github-actions)"
    target-branch: "develop"
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Paris"
    assignees:
      - "antoinezanardi"
    reviewers:
      - "antoinezanardi"
    commit-message:
      prefix: "chore(deps)"
    target-branch: "develop"
    open-pull-requests-limit: 20
    groups:
      commitlint:
        patterns:
          - "@commitlint*"
      nuxt:
        patterns:
          - "nuxt"
          - "@nuxt*"
      pinia:
        patterns:
          - "pinia*"
          - "@pinia*"
      playwright:
        patterns:
          - "playwright*"
          - "@playwright*"
      vitest:
        patterns:
          - "vitest*"
          - "@vitest*"
      stryker:
        patterns:
          - "@stryker-mutator*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "@typescript-eslint*"
          - "@stylistic/eslint-plugin"
          - "vue-eslint*"
      semantic-release:
        patterns:
          - "@semantic-release*"
      vue:
        patterns:
          - "vue*"
          - "@vue*"
      types:
        patterns:
          - "@types*"