const GAME_HISTORY_RECORD_ROLE_IMAGE_SIZE_OVER_MD = 70;

const GAME_HISTORY_RECORD_ROLE_IMAGE_SIZE_BELOW_MD = 56;

export {
  GAME_HISTORY_RECORD_ROLE_IMAGE_SIZE_OVER_MD,
  GAME_HISTORY_RECORD_ROLE_IMAGE_SIZE_BELOW_MD,
};