services:
  front:
    container_name: werewolves-assistant-web-preproduction-example
    depends_on:
      - api
    image: antoinezanardi/werewolves-assistant-web:local-preprod-en
    ports:
      - "3000:3000"
    restart: unless-stopped

  api:
    image: antoinezanardi/werewolves-assistant-api:latest
    container_name: werewolves-assistant-api-preproduction-example
    depends_on:
      - mongodb
    environment:
      ENVIRONMENT: "production"
      HOST: "0.0.0.0"
      PORT: "9292"
      DATABASE_HOST: "mongodb-preproduction-example"
      DATABASE_PORT: "27017"
      DATABASE_NAME: "werewolves-assistant"
      DATABASE_USERNAME: "preproduction"
      DATABASE_PASSWORD: "a_very_good_password"
    ports:
      - "9292:9292"
    restart: unless-stopped

  mongodb:
    container_name: mongodb-preproduction-example
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "preproduction"
      MONGO_INITDB_ROOT_PASSWORD: "a_very_good_password"
    volumes:
      - mongodb_data_container_preproduction_example:/data/db
    ports:
      - "29000:27017"
    restart: unless-stopped

volumes:
  mongodb_data_container_preproduction_example: