export default {
  cleanTempDir: "always",
  incremental: true,
  incrementalFile: "tests/stryker/incremental.json",
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  testRunner: "vitest",
  ignoreStatic: true,
  mutate: [
    "app.vue",
    "components/**/*.{ts,vue}",
    "composables/**/*.ts",
    "pages/**/*.{ts,vue}",
    "layouts/**/*.{ts,vue}",
    "stores/**/*.ts",
    "utils/**/*.ts",
  ],
  plugins: [
    "@stryker-mutator/vitest-runner",
    "@stryker-mutator/typescript-checker",
    "./config/stryker/plugins/stryker-define-props-ignorer-plugin.mjs",
    "./config/stryker/plugins/stryker-define-emits-ignorer-plugin.mjs",
    "./config/stryker/plugins/stryker-define-page-meta-ignorer-plugin.mjs",
    "./config/stryker/plugins/stryker-define-model-ignorer-plugin.mjs",
  ],
  ignorers: [
    "defineProps",
    "defineEmits",
    "definePageMeta",
    "defineModel",
  ],
  ignorePatterns: [
    "!.nuxt/",
    ".github/",
    ".husky/",
    ".output/",
    ".run/",
    ".idea/",
    "config/commitlint",
    "config/cucumber",
    "config/eslint",
    "config/lint-staged",
    "config/stryker",
    "scripts/",
    "server/",
    ".editorconfig",
    ".npmrc",
    ".nvmrc",
    ".releaserc.js",
    ".DS_Store",
    ".validate-branch-namerc.json",
    "CHANGELOG.md",
    "LICENSE",
    "pnpm-lock.yaml",
    "sonar-project.properties",
    "README.md",
  ],
  symlinkNodeModules: false,
  vitest: { configFile: "config/vitest/vitest.unit-config.ts" },
  reporters: ["clear-text", "progress", "html", "json"],
  htmlReporter: { fileName: "tests/stryker/coverage/index.html" },
  jsonReporter: { fileName: "tests/stryker/coverage/mutation.json" },
  thresholds: {
    high: 100,
    low: 100,
    break: 100,
  },
  disableTypeChecks: true,
};