const ACCEPTANCE_TESTS_PATH = "tests/acceptance";

const ACCEPTANCE_TESTS_PATH_SCREENSHOTS_PATH = `${ACCEPTANCE_TESTS_PATH}/screenshots`;

const ACCEPTANCE_TESTS_REPORTS_PATH = `${ACCEPTANCE_TESTS_PATH}/reports`;

const ACCEPTANCE_TESTS_REPORTS_SCREENSHOTS_PATH = `${ACCEPTANCE_TESTS_REPORTS_PATH}/screenshots`;

export {
  ACCEPTANCE_TESTS_PATH,
  ACCEPTANCE_TESTS_PATH_SCREENSHOTS_PATH,
  ACCEPTANCE_TESTS_REPORTS_PATH,
  ACCEPTANCE_TESTS_REPORTS_SCREENSHOTS_PATH,
};