#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no-install validate-branch-name;
npm run prettier:gherkin:fix;
npm run lint:staged:fix;
git add -A .;
npm run test:unit:staged;
npm run script:check-acceptance-features-shard;